name: Add new collection
description: Submit a new collection to a user
title: "[New collection]: "
labels: ["new collection", "content"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new collection! Please fill out the information below.
        
  - type: input
    id: user-id
    attributes:
      label: User ID
      description: The ID of the user this collection belongs to (will be created if it doesn't exist)
      placeholder: "e.g., johndoe"
    validations:
      required: true
      
  - type: input
    id: collection-id
    attributes:
      label: Collection ID
      description: A unique identifier for this collection (lowercase, no spaces, use hyphens)
      placeholder: "e.g., vintage-cameras"
    validations:
      required: true
      
  - type: input
    id: collection-name
    attributes:
      label: Collection name
      description: The display name for this collection
      placeholder: "e.g., Vintage Cameras"
    validations:
      required: true
      
  - type: textarea
    id: collection-description
    attributes:
      label: Description
      description: A description of the collection (supports Markdown)
      placeholder: |
        A curated collection of vintage film cameras from the 1960s-1980s.
    validations:
      required: false
      
  - type: input
    id: og-image
    attributes:
      label: OG image URL (optional)
      description: URL to an image for social media sharing
      placeholder: "/models/username/collectionname/og.jpeg"
    validations:
      required: false
      
  - type: textarea
    id: yaml-template
    attributes:
      label: Collection YAML
      description: Complete YAML representation of the collection
      placeholder: |
        id: "vintage-cameras"
        name: "Vintage Cameras"
        description: "A curated collection of vintage film cameras from the 1960s-1980s."
        og: "/models/johndoe/vintage-cameras/og.jpeg"
        items: []
      value: |
        id: "vintage-cameras"
        name: "Vintage Cameras"
        description: "A curated collection of vintage film cameras from the 1960s-1980s."
        og: "/models/johndoe/vintage-cameras/og.jpeg"
        items: []
      render: yaml
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        After submitting this issue:
        1. A maintainer will review your collection
        2. If the user doesn't exist, they will be created
        3. If approved, your collection will be added to the specified user in `src/manifest.tsx`
        4. You can then submit items for this collection
