/** Per-game studio, city, and first PlayStation 2 release. */

export const COLLECTION_DESCRIPTION =
  "[https://www.youtube.com/watch?v=AIcuALGM1TI&t=40s](https://www.youtube.com/watch?v=AIcuALGM1TI&t=40s)\n\n[https://vt.tiktok.com/ZSqNJo4Nn/](https://vt.tiktok.com/ZSqNJo4Nn/)";

export interface GameMeta {
  manufacturer: string;
  manufactureLocation: string;
  releaseDate: string;
}

/** Action Replay MAX / POWERSAVE cube — not a real game icon. */
export const AR_PLACEHOLDER_IDS = [
  'ape-escape-2',
  'bmx-2-save-game',
  'fmx-global',
  'gt3-game-data',
  'herdy-gerdy000042',
  'klonoa2lunateas-veil',
  'nfshp2',
  'rc-revenge-pro-saved-game',
  'resident-evilcodeveronicax',
  'silent-hill-3-file-icon',
  'smugglers-run-2hostileterritory',
  'spyro-enter-the-dragonfly',
  'terminator',
  'tm-black',
  'ty-the-tasmanian-tiger',
  'zone-of-the-enders',
] as const;

/** SHA-1 prefix of the AR cube's encoded PNG (36-vertex blue MAX / POWERSAVE / AR). */
export const AR_PLACEHOLDER_PNG_SHA1 = '6977e75f50e9';

export const GAME_META: Record<string, GameMeta> = {
  'ac04save-data': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 September 13' },
  'beyond-good-evil': { manufacturer: 'Ubisoft Montpellier', manufactureLocation: 'Montpellier, France', releaseDate: '2003 November 11' },
  'canis-canem-edit': { manufacturer: 'Rockstar Vancouver', manufactureLocation: 'Vancouver, Canada', releaseDate: '2006 October 17' },
  'cel-damage-eduardo': { manufacturer: 'Pseudo Interactive', manufactureLocation: 'Toronto, Canada', releaseDate: '2003 February 14' },
  'desa-gameeduardo': { manufacturer: 'Toys for Bob', manufactureLocation: 'Novato, California', releaseDate: '2003 September 4' },
  'zneo': { manufacturer: 'Spike', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 October 12' },
  'd3-profileeduardo': { manufacturer: 'Cavia', manufactureLocation: 'Tokyo, Japan', releaseDate: '2003 September 11' },
  'enter-the-matrix': { manufacturer: 'Shiny Entertainment', manufactureLocation: 'Newport Beach, California', releaseDate: '2003 May 15' },
  'futurama': { manufacturer: 'Unique Development Studios', manufactureLocation: 'Norrköping, Sweden', releaseDate: '2003 August 5' },
  'gran-turismo-4game-data': { manufacturer: 'Polyphony Digital', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 December 28' },
  'gta3': { manufacturer: 'DMA Design', manufactureLocation: 'Edinburgh, Scotland', releaseDate: '2001 October 23' },
  'sanandreas': { manufacturer: 'Rockstar North', manufactureLocation: 'Edinburgh, Scotland', releaseDate: '2004 October 26' },
  'gta-vicecity': { manufacturer: 'Rockstar North', manufactureLocation: 'Edinburgh, Scotland', releaseDate: '2002 October 27' },
  'gta-vcs': { manufacturer: 'Rockstar Leeds', manufactureLocation: 'Leeds, England', releaseDate: '2007 March 6' },
  'harry-potter-pda': { manufacturer: 'Eurocom', manufactureLocation: 'Derby, England', releaseDate: '2002 November 15' },
  'harrypotter': { manufacturer: 'Warthog Games', manufactureLocation: 'Manchester, England', releaseDate: '2003 December 12' },
  'harry-potter-pf': { manufacturer: 'Warthog Games', manufactureLocation: 'Manchester, England', releaseDate: '2003 December 12' },
  'jak-3': { manufacturer: 'Naughty Dog', manufactureLocation: 'Santa Monica, California', releaseDate: '2004 November 9' },
  'jak-and-daxter': { manufacturer: 'Naughty Dog', manufactureLocation: 'Santa Monica, California', releaseDate: '2001 December 3' },
  'jak-ii': { manufacturer: 'Naughty Dog', manufactureLocation: 'Santa Monica, California', releaseDate: '2003 October 14' },
  'killzoneeduardo': { manufacturer: 'Guerrilla Games', manufactureLocation: 'Amsterdam, Netherlands', releaseDate: '2004 November 2' },
  'king-kong': { manufacturer: 'Ubisoft Montpellier', manufactureLocation: 'Montpellier, France', releaseDate: '2005 November 22' },
  'maximo2e': { manufacturer: 'Capcom Production Studio 8', manufactureLocation: 'Sunnyvale, California', releaseDate: '2003 September 18' },
  'moheaeduardo': { manufacturer: 'EA Los Angeles', manufactureLocation: 'Los Angeles, California', releaseDate: '2005 June 7' },
  'moh-frontline-eduardo': { manufacturer: 'EA Los Angeles', manufactureLocation: 'Los Angeles, California', releaseDate: '2002 May 29' },
  'moh-rising-sunben': { manufacturer: 'EA Los Angeles', manufactureLocation: 'Los Angeles, California', releaseDate: '2003 November 11' },
  'moh-vanguardeduardo': { manufacturer: 'EA Los Angeles', manufactureLocation: 'Los Angeles, California', releaseDate: '2007 March 26' },
  'mgs2-15525plant-cleared': { manufacturer: 'Konami Computer Entertainment Japan', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 November 13' },
  'mgs3-game-data001': { manufacturer: 'Konami Computer Entertainment Japan', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 November 17' },
  'metalslug3': { manufacturer: 'SNK Playmore', manufactureLocation: 'Osaka, Japan', releaseDate: '2003 March 19' },
  'mmv4-options': { manufacturer: 'Supersonic Software', manufactureLocation: 'Royal Leamington Spa, England', releaseDate: '2006 June 27' },
  'motogp3file1': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2003 February 27' },
  'need-for-speed-underground': { manufacturer: 'EA Black Box', manufactureLocation: 'Vancouver, Canada', releaseDate: '2003 November 17' },
  'nfsu-2eduardo': { manufacturer: 'EA Black Box', manufactureLocation: 'Vancouver, Canada', releaseDate: '2004 November 9' },
  'outrun-2006coast2coast': { manufacturer: 'Sumo Digital', manufactureLocation: 'Sheffield, England', releaseDate: '2006 March 31' },
  'prince-of-persiasot-00-0332': { manufacturer: 'Ubisoft Montreal', manufactureLocation: 'Montreal, Canada', releaseDate: '2003 November 10' },
  'ratchet-clank': { manufacturer: 'Insomniac Games', manufactureLocation: 'Burbank, California', releaseDate: '2002 November 4' },
  'ratchet-clank-2': { manufacturer: 'Insomniac Games', manufactureLocation: 'Burbank, California', releaseDate: '2003 November 11' },
  'ratchet-clank-3': { manufacturer: 'Insomniac Games', manufactureLocation: 'Burbank, California', releaseDate: '2004 November 3' },
  'ratchet-clanksize-matters': { manufacturer: 'High Impact Games', manufactureLocation: 'Burbank, California', releaseDate: '2008 March 11' },
  'ratchet-gladiator': { manufacturer: 'Insomniac Games', manufactureLocation: 'Burbank, California', releaseDate: '2005 October 25' },
  'rez': { manufacturer: 'United Game Artists', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 November 22' },
  'secret-agent-clank': { manufacturer: 'High Impact Games', manufactureLocation: 'Burbank, California', releaseDate: '2009 May 26' },
  'shadowof-the-colossus': { manufacturer: 'Team Ico', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 October 18' },
  'silent-hill-3-file': { manufacturer: 'Team Silent', manufactureLocation: 'Tokyo, Japan', releaseDate: '2003 May 23' },
  'sly-2': { manufacturer: 'Sucker Punch Productions', manufactureLocation: 'Bellevue, Washington', releaseDate: '2004 September 14' },
  'sly-3': { manufacturer: 'Sucker Punch Productions', manufactureLocation: 'Bellevue, Washington', releaseDate: '2005 September 26' },
  'sly-raccoon': { manufacturer: 'Sucker Punch Productions', manufactureLocation: 'Bellevue, Washington', releaseDate: '2002 September 23' },
  'smugglers-run': { manufacturer: 'Angel Studios', manufactureLocation: 'Carlsbad, California', releaseDate: '2000 October 26' },
  'spiderman-2': { manufacturer: 'Treyarch', manufactureLocation: 'Santa Monica, California', releaseDate: '2004 June 28' },
  'splinter-cell': { manufacturer: 'Ubisoft Shanghai', manufactureLocation: 'Shanghai, China', releaseDate: '2003 April 8' },
  'tekken-4': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2002 March 28' },
  'tekken-5': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 February 24' },
  'the-getaway': { manufacturer: 'Team Soho', manufactureLocation: 'London, England', releaseDate: '2002 December 11' },
  'the-returnof-the-king': { manufacturer: 'EA Redwood Shores', manufactureLocation: 'Redwood City, California', releaseDate: '2003 November 5' },
  'timesplitters-2saved-maps': { manufacturer: 'Free Radical Design', manufactureLocation: 'Nottingham, England', releaseDate: '2002 October 8' },
  'tomb-raideraodsave-data': { manufacturer: 'Core Design', manufactureLocation: 'Derby, England', releaseDate: '2003 June 20' },
  'thaw-progresseduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2005 October 18' },
  'thaw-graphicgrafiti': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2005 October 18' },
  'thps3-skatereduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2001 November 15' },
  'thps3-options-and-pro-careers': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2001 November 15' },
  'thps4-skatereduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2002 October 23' },
  'thps4-careereduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2002 October 23' },
  'thug-skatereduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2003 October 27' },
  'thug-2-skatereduardo': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2004 October 4' },
  'thug-2-graphicgraphic': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2004 October 4' },
  "katamari-damacy": { manufacturer: "Namco", manufactureLocation: "Tokyo, Japan", releaseDate: "2004 March 18" },
  "we-love-katamari": { manufacturer: "Namco", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 July 6" },
  "god-of-war": { manufacturer: "SCE Santa Monica Studio", manufactureLocation: "Santa Monica, California", releaseDate: "2005 March 22" },
  "god-of-war-2": { manufacturer: "SCE Santa Monica Studio", manufactureLocation: "Santa Monica, California", releaseDate: "2007 March 13" },
  "ico": { manufacturer: "Team Ico", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 September 24" },
  "okami": { manufacturer: "Clover Studio", manufactureLocation: "Osaka, Japan", releaseDate: "2006 April 20" },
  "persona-3": { manufacturer: "Atlus", manufactureLocation: "Tokyo, Japan", releaseDate: "2006 July 13" },
  "persona-4": { manufacturer: "Atlus", manufactureLocation: "Tokyo, Japan", releaseDate: "2008 July 10" },
  "kingdom-hearts": { manufacturer: "Square", manufactureLocation: "Tokyo, Japan", releaseDate: "2002 March 28" },
  "kingdom-hearts-2": { manufacturer: "Square Enix", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 December 22" },
  "final-fantasy-x": { manufacturer: "Square", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 July 19" },
  "final-fantasy-xii": { manufacturer: "Square Enix", manufactureLocation: "Tokyo, Japan", releaseDate: "2006 March 16" },
  "devil-may-cry": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2001 August 23" },
  "devil-may-cry-3": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2005 February 17" },
  "resident-evil-4": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2005 January 11" },
  "silent-hill-2": { manufacturer: "Team Silent", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 September 24" },
  "burnout-3": { manufacturer: "Criterion Games", manufactureLocation: "Guildford, England", releaseDate: "2004 September 8" },
  "ssx-3": { manufacturer: "EA Canada", manufactureLocation: "Burnaby, Canada", releaseDate: "2003 October 20" },
  "guitar-hero": { manufacturer: "Harmonix", manufactureLocation: "Boston, Massachusetts", releaseDate: "2005 November 8" },
  "psychonauts": { manufacturer: "Double Fine Productions", manufactureLocation: "San Francisco, California", releaseDate: "2005 April 19" },
  "viewtiful-joe": { manufacturer: "Clover Studio", manufactureLocation: "Osaka, Japan", releaseDate: "2003 June 26" },
  "dark-cloud": { manufacturer: "Level-5", manufactureLocation: "Fukuoka, Japan", releaseDate: "2000 December 14" },
  "dark-chronicle": { manufacturer: "Level-5", manufactureLocation: "Fukuoka, Japan", releaseDate: "2002 November 28" },
  "frequency": { manufacturer: "Harmonix", manufactureLocation: "Boston, Massachusetts", releaseDate: "2001 November 19" },
  "amplitude": { manufacturer: "Harmonix", manufactureLocation: "Boston, Massachusetts", releaseDate: "2003 March 24" },
  "killer7": { manufacturer: "Grasshopper Manufacture", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 June 9" },
  "god-hand": { manufacturer: "Clover Studio", manufactureLocation: "Osaka, Japan", releaseDate: "2006 September 14" },
  "the-warriors": { manufacturer: "Rockstar Toronto", manufactureLocation: "Oakville, Canada", releaseDate: "2005 October 17" },
  "manhunt": { manufacturer: "Rockstar North", manufactureLocation: "Edinburgh, Scotland", releaseDate: "2003 November 18" },
  "zone-of-the-enders-2": { manufacturer: "Konami Computer Entertainment Japan", manufactureLocation: "Tokyo, Japan", releaseDate: "2003 February 13" },
  "crash-twinsanity": { manufacturer: "Traveller's Tales", manufactureLocation: "Knutsford, England", releaseDate: "2004 September 28" },
  "simpsons-hit-and-run": { manufacturer: "Radical Entertainment", manufactureLocation: "Vancouver, Canada", releaseDate: "2003 September 16" },
  "black": { manufacturer: "Criterion Games", manufactureLocation: "Guildford, England", releaseDate: "2006 February 28" },
  "soulcalibur-2": { manufacturer: "Project Soul", manufactureLocation: "Tokyo, Japan", releaseDate: "2002 July 30" },
  "ace-combat-5": { manufacturer: "Namco", manufactureLocation: "Tokyo, Japan", releaseDate: "2004 October 21" },
  "fatal-frame": { manufacturer: "Tecmo", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 December 13" },
  "onimusha": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2001 January 25" },
  "red-dead-revolver": { manufacturer: "Rockstar San Diego", manufactureLocation: "Carlsbad, California", releaseDate: "2004 May 4" },
  "shadow-of-rome": { manufacturer: "Capcom Production Studio 4", manufactureLocation: "Osaka, Japan", releaseDate: "2005 February 8" },
  "ape-escape-3": { manufacturer: "SCE Japan Studio", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 July 14" },
  "blood-will-tell": { manufacturer: "Wow Entertainment", manufactureLocation: "Tokyo, Japan", releaseDate: "2004 July 29" },
  "burnout-revenge": { manufacturer: "Criterion Games", manufactureLocation: "Guildford, England", releaseDate: "2005 September 13" },
  "ape-escape-2": { manufacturer: "SCE Japan Studio", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 July 18" },
  "clock-tower-3": { manufacturer: "Capcom Production Studio 3", manufactureLocation: "Osaka, Japan", releaseDate: "2002 December 12" },
  "devil-may-cry-2": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2003 January 25" },
  "disgaea": { manufacturer: "Nippon Ichi Software", manufactureLocation: "Kofu, Japan", releaseDate: "2003 January 30" },
  "dragon-quest-viii": { manufacturer: "Level-5", manufactureLocation: "Fukuoka, Japan", releaseDate: "2004 November 27" },
  "fatal-frame-2": { manufacturer: "Tecmo", manufactureLocation: "Tokyo, Japan", releaseDate: "2003 November 27" },
  "fatal-frame-3": { manufacturer: "Tecmo", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 July 28" },
  "final-fantasy-x-2": { manufacturer: "Square", manufactureLocation: "Tokyo, Japan", releaseDate: "2003 March 13" },
  "gitaroo-man": { manufacturer: "iNiS", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 June 21" },
  "gran-turismo-3": { manufacturer: "Polyphony Digital", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 April 28" },
  "guitar-hero-2": { manufacturer: "Harmonix", manufactureLocation: "Boston, Massachusetts", releaseDate: "2006 November 7" },
  "haunting-ground": { manufacturer: "Capcom Production Studio 1", manufactureLocation: "Osaka, Japan", releaseDate: "2005 April 21" },
  "hitman-2": { manufacturer: "IO Interactive", manufactureLocation: "Copenhagen, Denmark", releaseDate: "2002 October 1" },
  "kuon": { manufacturer: "FromSoftware", manufactureLocation: "Tokyo, Japan", releaseDate: "2004 April 1" },
  "max-payne-2": { manufacturer: "Remedy Entertainment", manufactureLocation: "Espoo, Finland", releaseDate: "2003 December 2" },
  "midnight-club-3": { manufacturer: "Rockstar San Diego", manufactureLocation: "Carlsbad, California", releaseDate: "2005 April 11" },
  "need-for-speed-most-wanted": { manufacturer: "EA Black Box", manufactureLocation: "Vancouver, Canada", releaseDate: "2005 November 15" },
  "odin-sphere": { manufacturer: "Vanillaware", manufactureLocation: "Osaka, Japan", releaseDate: "2007 May 17" },
  "okage": { manufacturer: "Zener Works", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 March 15" },
  "parappa-2": { manufacturer: "NanaOn-Sha", manufactureLocation: "Tokyo, Japan", releaseDate: "2001 August 30" },
  "persona-3-fes": { manufacturer: "Atlus", manufactureLocation: "Tokyo, Japan", releaseDate: "2007 April 19" },
  "resident-evil-code-veronica": { manufacturer: "Capcom", manufactureLocation: "Osaka, Japan", releaseDate: "2001 March 22" },
  "rogue-galaxy": { manufacturer: "Level-5", manufactureLocation: "Fukuoka, Japan", releaseDate: "2005 December 8" },
  "rule-of-rose": { manufacturer: "Punchline", manufactureLocation: "Tokyo, Japan", releaseDate: "2006 January 19" },
  "smt-nocturne": { manufacturer: "Atlus", manufactureLocation: "Tokyo, Japan", releaseDate: "2003 February 20" },
  "silent-hill-4": { manufacturer: "Team Silent", manufactureLocation: "Tokyo, Japan", releaseDate: "2004 June 17" },
  "siren": { manufacturer: "SCE Japan Studio", manufactureLocation: "Tokyo, Japan", releaseDate: "2003 November 6" },
  "soulcalibur-3": { manufacturer: "Project Soul", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 November 23" },
  "space-channel-5-part-2": { manufacturer: "United Game Artists", manufactureLocation: "Tokyo, Japan", releaseDate: "2002 February 14" },
  "ssx-tricky": { manufacturer: "EA Canada", manufactureLocation: "Burnaby, Canada", releaseDate: "2001 November 5" },
  "star-wars-battlefront-2": { manufacturer: "Pandemic Studios", manufactureLocation: "Los Angeles, California", releaseDate: "2005 November 1" },
  "tales-of-the-abyss": { manufacturer: "Namco Tales Studio", manufactureLocation: "Tokyo, Japan", releaseDate: "2005 December 15" },
  "splinter-cell-chaos-theory": { manufacturer: "Ubisoft Montreal", manufactureLocation: "Montreal, Canada", releaseDate: "2005 March 28" },
  "timesplitters-future-perfect": { manufacturer: "Free Radical Design", manufactureLocation: "Nottingham, England", releaseDate: "2005 March 21" },
  "wipeout-fusion": { manufacturer: "Studio Liverpool", manufactureLocation: "Liverpool, England", releaseDate: "2002 February 8" },
  "xenosaga": { manufacturer: "Monolith Soft", manufactureLocation: "Tokyo, Japan", releaseDate: "2002 February 28" },
  'xiii-dataxiii': { manufacturer: 'Ubisoft Paris', manufactureLocation: 'Paris, France', releaseDate: '2003 November 18' },
  'ace-combat-zero': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 March 23' },
  'armored-core-3': { manufacturer: 'FromSoftware', manufactureLocation: 'Tokyo, Japan', releaseDate: '2002 April 23' },
  'ar-tonelico': { manufacturer: 'Gust', manufactureLocation: 'Nagano, Japan', releaseDate: '2006 January 26' },
  'auto-modellista': { manufacturer: 'Capcom', manufactureLocation: 'Osaka, Japan', releaseDate: '2002 August 22' },
  'baldurs-gate-dark-alliance': { manufacturer: 'Snowblind Studios', manufactureLocation: 'Bothell, Washington', releaseDate: '2001 December 2' },
  'bloodrayne': { manufacturer: 'Terminal Reality', manufactureLocation: 'Lewisville, Texas', releaseDate: '2002 October 31' },
  'burnout-2': { manufacturer: 'Criterion Games', manufactureLocation: 'Guildford, England', releaseDate: '2002 September 30' },
  'call-of-duty-finest-hour': { manufacturer: 'Spark Unlimited', manufactureLocation: 'Sherman Oaks, California', releaseDate: '2004 November 16' },
  'capcom-vs-snk-2': { manufacturer: 'Capcom', manufactureLocation: 'Osaka, Japan', releaseDate: '2001 September 13' },
  'castlevania-curse-of-darkness': { manufacturer: 'Konami Computer Entertainment Tokyo', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 November 1' },
  'castlevania-lament-of-innocence': { manufacturer: 'Konami Computer Entertainment Tokyo', manufactureLocation: 'Tokyo, Japan', releaseDate: '2003 October 21' },
  'champions-of-norrath': { manufacturer: 'Snowblind Studios', manufactureLocation: 'Bothell, Washington', releaseDate: '2004 February 10' },
  'cold-fear': { manufacturer: 'Darkworks', manufactureLocation: 'Paris, France', releaseDate: '2005 March 15' },
  'crash-wrath-of-cortex': { manufacturer: 'Traveller\'s Tales', manufactureLocation: 'Knutsford, England', releaseDate: '2001 October 29' },
  'crazy-taxi': { manufacturer: 'Hitmaker', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 May 17' },
  'dead-or-alive-2': { manufacturer: 'Team Ninja', manufactureLocation: 'Tokyo, Japan', releaseDate: '2000 March 30' },
  'def-jam-fight-for-ny': { manufacturer: 'AKI Corporation', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 September 20' },
  'digital-devil-saga': { manufacturer: 'Atlus', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 April 15' },
  'digital-devil-saga-2': { manufacturer: 'Atlus', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 January 27' },
  'dirge-of-cerberus': { manufacturer: 'Square Enix', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 January 26' },
  'disgaea-2': { manufacturer: 'Nippon Ichi Software', manufactureLocation: 'Kofu, Japan', releaseDate: '2006 February 23' },
  'hack-infection': { manufacturer: 'CyberConnect2', manufactureLocation: 'Fukuoka, Japan', releaseDate: '2002 June 20' },
  'dragon-ball-z-budokai-3': { manufacturer: 'Dimps', manufactureLocation: 'Osaka, Japan', releaseDate: '2004 November 16' },
  'drakengard-2': { manufacturer: 'Cavia', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 June 16' },
  'driver-3': { manufacturer: 'Reflections Interactive', manufactureLocation: 'Newcastle, England', releaseDate: '2004 June 21' },
  'genji': { manufacturer: 'Game Republic', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 January 20' },
  'getaway-black-monday': { manufacturer: 'Team Soho', manufactureLocation: 'London, England', releaseDate: '2004 November 12' },
  'godfather': { manufacturer: 'EA Redwood Shores', manufactureLocation: 'Redwood City, California', releaseDate: '2006 March 21' },
  'gradius-v': { manufacturer: 'Treasure', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 July 22' },
  'gta-lcs': { manufacturer: 'Rockstar Leeds', manufactureLocation: 'Leeds, England', releaseDate: '2005 October 25' },
  'guilty-gear-x2': { manufacturer: 'Arc System Works', manufactureLocation: 'Yokohama, Japan', releaseDate: '2002 May 23' },
  'guitar-hero-3': { manufacturer: 'Neversoft', manufactureLocation: 'Woodland Hills, California', releaseDate: '2007 October 28' },
  'hitman-blood-money': { manufacturer: 'IO Interactive', manufactureLocation: 'Copenhagen, Denmark', releaseDate: '2006 May 30' },
  'jak-x': { manufacturer: 'Naughty Dog', manufactureLocation: 'Santa Monica, California', releaseDate: '2005 October 18' },
  'kingdom-hearts-re-com': { manufacturer: 'Square Enix', manufactureLocation: 'Tokyo, Japan', releaseDate: '2007 March 29' },
  'klonoa-2': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 March 22' },
  'lego-star-wars': { manufacturer: 'Traveller\'s Tales', manufactureLocation: 'Knutsford, England', releaseDate: '2005 April 2' },
  'manhunt-2': { manufacturer: 'Rockstar London', manufactureLocation: 'London, England', releaseDate: '2007 October 29' },
  'mark-of-kri': { manufacturer: 'SCE San Diego Studio', manufactureLocation: 'San Diego, California', releaseDate: '2002 November 11' },
  'mortal-kombat-deception': { manufacturer: 'Midway Games', manufactureLocation: 'Chicago, Illinois', releaseDate: '2004 October 4' },
  'nba-street-vol-2': { manufacturer: 'EA Canada', manufactureLocation: 'Burnaby, Canada', releaseDate: '2003 April 28' },
  'need-for-speed-carbon': { manufacturer: 'EA Black Box', manufactureLocation: 'Vancouver, Canada', releaseDate: '2006 October 30' },
  'onimusha-2': { manufacturer: 'Capcom', manufactureLocation: 'Osaka, Japan', releaseDate: '2002 March 7' },
  'onimusha-3': { manufacturer: 'Capcom', manufactureLocation: 'Osaka, Japan', releaseDate: '2004 February 26' },
  'phantom-brave': { manufacturer: 'Nippon Ichi Software', manufactureLocation: 'Kofu, Japan', releaseDate: '2004 January 22' },
  'primal': { manufacturer: 'SCE Studio Cambridge', manufactureLocation: 'Cambridge, England', releaseDate: '2003 March 25' },
  'prince-of-persia-two-thrones': { manufacturer: 'Ubisoft Montreal', manufactureLocation: 'Montreal, Canada', releaseDate: '2005 December 1' },
  'prince-of-persia-warrior-within': { manufacturer: 'Ubisoft Montreal', manufactureLocation: 'Montreal, Canada', releaseDate: '2004 November 30' },
  'psi-ops': { manufacturer: 'Midway Games', manufactureLocation: 'San Diego, California', releaseDate: '2004 June 14' },
  'punisher': { manufacturer: 'Volition', manufactureLocation: 'Champaign, Illinois', releaseDate: '2005 January 18' },
  'radiata-stories': { manufacturer: 'tri-Ace', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 January 27' },
  'red-faction-2': { manufacturer: 'Volition', manufactureLocation: 'Champaign, Illinois', releaseDate: '2002 October 15' },
  'resident-evil-outbreak': { manufacturer: 'Capcom', manufactureLocation: 'Osaka, Japan', releaseDate: '2003 December 11' },
  'ridge-racer-v': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2000 March 4' },
  'scarface': { manufacturer: 'Radical Entertainment', manufactureLocation: 'Vancouver, Canada', releaseDate: '2006 October 8' },
  'second-sight': { manufacturer: 'Free Radical Design', manufactureLocation: 'Nottingham, England', releaseDate: '2004 September 3' },
  'shadow-hearts': { manufacturer: 'Sacnoth', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 June 28' },
  'shadow-hearts-covenant': { manufacturer: 'Nautilus', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 February 19' },
  'shinobi': { manufacturer: 'Overworks', manufactureLocation: 'Tokyo, Japan', releaseDate: '2002 November 10' },
  'siren-2': { manufacturer: 'SCE Japan Studio', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 February 9' },
  'socom': { manufacturer: 'Zipper Interactive', manufactureLocation: 'Redmond, Washington', releaseDate: '2002 August 27' },
  'spider-man': { manufacturer: 'Treyarch', manufactureLocation: 'Santa Monica, California', releaseDate: '2002 April 15' },
  'spongebob-bikini-bottom': { manufacturer: 'Heavy Iron Studios', manufactureLocation: 'Los Angeles, California', releaseDate: '2003 October 31' },
  'star-ocean-3': { manufacturer: 'tri-Ace', manufactureLocation: 'Tokyo, Japan', releaseDate: '2003 February 27' },
  'suffering': { manufacturer: 'Surreal Software', manufactureLocation: 'Seattle, Washington', releaseDate: '2004 March 9' },
  'suikoden-v': { manufacturer: 'Konami', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 February 23' },
  'tekken-tag': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2000 March 4' },
  'tenchu-wrath-of-heaven': { manufacturer: 'K2', manufactureLocation: 'Osaka, Japan', releaseDate: '2003 March 3' },
  'timesplitters-1': { manufacturer: 'Free Radical Design', manufactureLocation: 'Nottingham, England', releaseDate: '2000 October 26' },
  'true-crime-streets-of-la': { manufacturer: 'Luxoflux', manufactureLocation: 'Santa Monica, California', releaseDate: '2003 November 3' },
  'twisted-metal-black': { manufacturer: 'Incognito Entertainment', manufactureLocation: 'Salt Lake City, Utah', releaseDate: '2001 June 18' },
  'urban-reign': { manufacturer: 'Namco', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 September 13' },
  'viewtiful-joe-2': { manufacturer: 'Clover Studio', manufactureLocation: 'Osaka, Japan', releaseDate: '2004 November 18' },
  'virtua-fighter-4': { manufacturer: 'Sega-AM2', manufactureLocation: 'Tokyo, Japan', releaseDate: '2002 January 31' },
  'wwe-here-comes-the-pain': { manufacturer: 'Yuke\'s', manufactureLocation: 'Osaka, Japan', releaseDate: '2003 October 27' },
  'xenosaga-2': { manufacturer: 'Monolith Soft', manufactureLocation: 'Tokyo, Japan', releaseDate: '2004 June 24' },
  'xenosaga-3': { manufacturer: 'Monolith Soft', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 July 6' },
  'yakuza': { manufacturer: 'Sega CS1', manufactureLocation: 'Tokyo, Japan', releaseDate: '2005 December 8' },
  'yakuza-2': { manufacturer: 'Sega CS1', manufactureLocation: 'Tokyo, Japan', releaseDate: '2006 December 7' },
  'zone-of-the-enders': { manufacturer: 'Konami Computer Entertainment Japan', manufactureLocation: 'Tokyo, Japan', releaseDate: '2001 March 1' },
};
