#!/usr/bin/env python3
"""Read src/manifest.ts + src/ps2-archive.ts and emit tools/og_groups.bzl.

User/collection OG images cannot be inferred from GLB filenames
(ps2_save-icons_*.glb belong to user mbo, max2_friends_zoe.glb is in
mbo/friends, etc.), so this walks the first-party manifest instead.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

MODEL_RE = re.compile(r'model:\s*"/assets/goldens/([^"]+\.glb)"')
ID_RE = re.compile(r'^(\s*)id:\s*"([^"]+)"')
OG_RE = re.compile(r'^(\s*)og:\s*"/assets/derived/([^"]+)"')
PS2_REF_RE = re.compile(r"^\s+PS2_SAVE_ICONS_COLLECTION,?$")
MANIFEST_START = "export const FIRST_PARTY_MANIFEST"

# 4 spaces = user, 8 = collection, 12 = item (manifest.ts style).
USER_INDENT = 4
COLLECTION_INDENT = 8


def _repo_root() -> Path:
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if workspace:
        return Path(workspace)
    testdir = os.environ.get("TEST_SRCDIR")
    if testdir:
        return Path(testdir) / os.environ.get("TEST_WORKSPACE", "_main")
    return Path(__file__).resolve().parent.parent


def parse_ps2_archive(text: str) -> tuple[str, str, list[str]]:
    collection_id = "ps2-save-icons"
    og = "mbo_ps2-save-icons_og.png"
    id_match = re.search(r'^\s+id:\s*"([^"]+)"', text, re.M)
    og_match = re.search(r'^\s+og:\s*"/assets/derived/([^"]+)"', text, re.M)
    if id_match:
        collection_id = id_match.group(1)
    if og_match:
        og = og_match.group(1)
    models = MODEL_RE.findall(text)
    return collection_id, og, models


def _active_lines(block: str) -> list[str]:
    """Drop full-line comments; keep the FIRST_PARTY_MANIFEST array only."""
    start = block.find(MANIFEST_START)
    if start < 0:
        raise ValueError("FIRST_PARTY_MANIFEST not found")
    rest = block[start:]
    end = rest.find("\n];")
    if end < 0:
        raise ValueError("FIRST_PARTY_MANIFEST terminator not found")
    body = rest[: end + 3]
    lines = []
    for line in body.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("//"):
            continue
        lines.append(line)
    return lines


def parse_manifest(manifest_text: str, ps2_text: str) -> dict:
    ps2_id, ps2_og, ps2_models = parse_ps2_archive(ps2_text)
    users: dict[str, dict] = {}
    user_id: str | None = None
    collection_id: str | None = None

    def ensure_user(uid: str) -> dict:
        return users.setdefault(
            uid,
            {"og": f"{uid}_og.png", "collections": {}},
        )

    def ensure_collection(uid: str, cid: str) -> dict:
        user = ensure_user(uid)
        return user["collections"].setdefault(
            cid,
            {"og": f"{uid}_{cid}_og.png", "models": []},
        )

    for line in _active_lines(manifest_text):
        if PS2_REF_RE.match(line):
            if user_id is None:
                raise ValueError("PS2_SAVE_ICONS_COLLECTION outside a user")
            collection_id = ps2_id
            coll = ensure_collection(user_id, collection_id)
            coll["og"] = ps2_og
            coll["models"] = list(ps2_models)
            continue

        id_match = ID_RE.match(line)
        if id_match:
            indent = len(id_match.group(1).replace("\t", "    "))
            ident = id_match.group(2)
            if indent == USER_INDENT:
                user_id = ident
                collection_id = None
                ensure_user(user_id)
            elif indent == COLLECTION_INDENT:
                if user_id is None:
                    raise ValueError(f"collection id {ident!r} outside a user")
                collection_id = ident
                ensure_collection(user_id, collection_id)
            continue

        og_match = OG_RE.match(line)
        if og_match and user_id:
            indent = len(og_match.group(1).replace("\t", "    "))
            og_name = og_match.group(2)
            if indent == USER_INDENT:
                ensure_user(user_id)["og"] = og_name
            elif indent == COLLECTION_INDENT and collection_id:
                ensure_collection(user_id, collection_id)["og"] = og_name
            continue

        model_match = MODEL_RE.search(line)
        if model_match:
            if user_id is None or collection_id is None:
                raise ValueError(f"model {model_match.group(1)!r} outside a collection")
            ensure_collection(user_id, collection_id)["models"].append(model_match.group(1))

    return users


def format_bzl(users: dict) -> str:
    lines = [
        "# Generated by tools/emit_og_groups.py — do not edit.",
        "# Regenerated with: bazel run //tools:emit_og_groups",
        "",
        "# (output png basename, [glb filenames under public/assets/goldens/])",
        "USER_OGS = [",
    ]
    for uid, user in users.items():
        models = []
        for coll in user["collections"].values():
            models.extend(coll["models"])
        if not models:
            continue
        lines.append(f"    ({_starlark_str(user['og'])}, [")
        for model in models:
            lines.append(f"        {_starlark_str(model)},")
        lines.append("    ]),")
    lines.append("]")
    lines.append("")
    lines.append("COLLECTION_OGS = [")
    for uid, user in users.items():
        for cid, coll in user["collections"].items():
            if not coll["models"]:
                continue
            lines.append(f"    ({_starlark_str(coll['og'])}, [")
            for model in coll["models"]:
                lines.append(f"        {_starlark_str(model)},")
            lines.append("    ]),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _starlark_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_groups(root: Path | None = None) -> dict:
    root = root or _repo_root()
    manifest = (root / "src" / "manifest.ts").read_text()
    ps2 = (root / "src" / "ps2-archive.ts").read_text()
    return parse_manifest(manifest, ps2)


def main(argv: list[str]) -> int:
    root = _repo_root()
    users = load_groups(root)
    out_path = Path(argv[1]) if len(argv) > 1 else root / "tools" / "og_groups.bzl"
    if not out_path.is_absolute():
        out_path = root / out_path
    out_path.write_text(format_bzl(users))
    n_users = sum(1 for u in users.values() if any(c["models"] for c in u["collections"].values()))
    n_coll = sum(1 for u in users.values() for c in u["collections"].values() if c["models"])
    n_models = sum(len(c["models"]) for u in users.values() for c in u["collections"].values())
    print(f"Wrote {out_path} ({n_users} users, {n_coll} collections, {n_models} models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
